In [15]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [5]:
%pwd

'/home/binardo/git/ML_pro/Module 1 IA Méthodo/1.5-methodologie-de-l-IA/06_Projets finaux/ML__Pro_Real_estate_Price_Prediction'

In [36]:
df = pd.read_csv('data/kaggle_train_set.csv')

df

,OverallQual,GrLivArea,TotalBsmtSF,1stFlrSF,YearBuilt,YearRemodAdd,GarageCars,GarageArea,FullBath,TotRmsAbvGrd,KitchenQual,Fireplaces,LotArea,Neighborhood,ExterQual,SalePrice
0,7,1710,856,856,2003,2003,2,548,2,8,Gd,0,8450,CollgCr,Gd,208500
1,6,1262,1262,1262,1976,1976,2,460,2,6,TA,1,9600,Veenker,TA,181500
2,7,1786,920,920,2001,2002,2,608,2,6,Gd,1,11250,CollgCr,Gd,223500
3,8,1694,1686,1694,2004,2005,2,636,2,7,Gd,1,10084,Somerst,Gd,307000
4,7,1774,952,1022,1931,1950,2,468,2,8,TA,2,6120,OldTown,TA,129900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,5,1072,547,1072,2005,2005,2,525,1,5,TA,0,3675,Edwards,TA,145000
1176,7,1221,1221,1221,2004,2005,2,400,2,6,Gd,0,7500,Somerst,Gd,185000
1177,6,1647,953,953,1999,2000,2,460,2,7,TA,1,7917,Gilbert,TA,175000
1178,7,2340,1152,1188,1941,2006,1,252,2,9,Gd,2,9042,Crawfor,Ex,266500
1179,5,1078,1078,1078,1950,1996,1,240,1,5,Gd,0,9717,NAmes,TA,142125

In [8]:
df.describe()

,OverallQual,GrLivArea,TotalBsmtSF,1stFlrSF,YearBuilt,YearRemodAdd,GarageCars,GarageArea,FullBath,TotRmsAbvGrd,Fireplaces,LotArea,SalePrice
count,1180.000000,1180.000000,1180.000000,1180.000000,1180.000000,1180.000000,1180.000000,1180.000000,1180.000000,1180.000000,1180.000000,1180.000000,1180.000000
mean,6.095763,1508.277966,1058.874576,1163.179661,1970.688983,1984.511017,1.752542,468.944915,1.552542,6.486441,0.609322,10448.989831,179822.169492
std,1.383956,534.634371,448.648614,395.100829,30.002104,20.775770,0.750314,211.898970,0.549302,1.630078,0.650502,10266.492616,79703.346024
min,1.000000,334.000000,0.000000,334.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,2.000000,0.000000,1300.000000,34900.000000
25%,5.000000,1118.000000,793.000000,879.750000,1953.000000,1966.000000,1.000000,312.000000,1.000000,5.000000,0.000000,7500.000000,128800.000000
50%,6.000000,1441.500000,993.500000,1088.000000,1972.000000,1993.000000,2.000000,474.000000,2.000000,6.000000,1.000000,9458.500000,161250.000000
75%,7.000000,1779.000000,1309.500000,1392.000000,2000.000000,2004.000000,2.000000,576.000000,2.000000,7.000000,1.000000,11532.750000,212000.000000
max,10.000000,5642.000000,6110.000000,4692.000000,2010.000000,2010.000000,4.000000,1418.000000,3.000000,14.000000,3.000000,215245.000000,755000.000000

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1180 entries, 0 to 1179
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OverallQual   1180 non-null   int64
 1   GrLivArea     1180 non-null   int64
 2   TotalBsmtSF   1180 non-null   int64
 3   1stFlrSF      1180 non-null   int64
 4   YearBuilt     1180 non-null   int64
 5   YearRemodAdd  1180 non-null   int64
 6   GarageCars    1180 non-null   int64
 7   GarageArea    1180 non-null   int64
 8   FullBath      1180 non-null   int64
 9   TotRmsAbvGrd  1180 non-null   int64
 10  KitchenQual   1180 non-null   str
 11  Fireplaces    1180 non-null   int64
 12  LotArea       1180 non-null   int64
 13  Neighborhood  1180 non-null   str
 14  ExterQual     1180 non-null   str
 15  SalePrice     1180 non-null   int64
dtypes: int64(13), str(3)
memory usage: 147.6 KB

- Almost entirely numeric columns. 
- Only 3 categorical columns to encode: "Neighborhood", "ExterQual", "KitchenQual". The encoding type needs to be determined: OneHot or Ordinal.

- Clean dataset; no null values ​​in any column, so no need to handle NaNs.

In [10]:
df['KitchenQual'].value_counts()

KitchenQual
TA    600
Gd    462
Ex     84
Fa     34
Name: count, dtype: int64

In [11]:
df['ExterQual'].value_counts()

ExterQual
TA    742
Gd    383
Ex     44
Fa     11
Name: count, dtype: int64

"ExterQual" & "KitchenQual" have a clear Hierarchical order.

TA : TA = Typical/Average.

Fa : Fair

Gd : Good

Ex : Excellent

So ordinal order : Po < Fa < TA < Gd < Ex.

In [12]:
df['Neighborhood'].value_counts()

Neighborhood
NAmes      198
CollgCr    120
OldTown     91
Edwards     76
Somerst     67
Sawyer      62
NridgHt     61
Gilbert     59
NWAmes      57
SawyerW     51
BrkSide     50
Crawfor     43
Mitchel     36
NoRidge     33
Timber      29
IDOTRR      24
ClearCr     23
SWISU       21
StoneBr     18
Blmngtn     16
BrDale      15
MeadowV     13
Veenker     10
NPkVill      5
Blueste      2
Name: count, dtype: int64

In [13]:
df['Neighborhood'].unique()

<StringArray>
['CollgCr', 'Veenker', 'Somerst', 'OldTown', 'BrkSide', 'NridgHt',  'Sawyer',
   'NAmes', 'SawyerW',  'IDOTRR', 'Edwards',  'Timber', 'Mitchel', 'Gilbert',
 'StoneBr', 'ClearCr', 'Crawfor',  'NWAmes', 'NPkVill', 'Blmngtn',  'BrDale',
 'NoRidge',   'SWISU', 'MeadowV', 'Blueste']
Length: 25, dtype: str

The neighborhoods surely have different qualities, and a resident familiar with the city would clearly understand the hierarchy between them. 

However, in the absence of information about these neighborhoods (presumably a fictional city?), we can't create an ordinal hierarchy without it. 
OneHot encoding seems like the best solution. 
But since there are 25 different neighborhoods, this would add 25 new columns (or 24 if we drop one). Does this add too many new columns ?

With approximately 1460 rows (standard Kaggle dataset), 25 additional columns are perfectly acceptable—the rule of thumb is to have at least 5-10 times more rows than columns, and wea re well above that.

The "multicorrelation" is actually the dummy variable trap: if we keep 25 columns instead of 24, one column is perfectly predictable by the others. Sklearn has a `drop='first'` parameter in OneHotEncoder to prevent this.

This problem only applies to linear models (LinearRegression). For Random Forest or XGBoost, the 25 columns pose no problem.

### 1 Preprocessing

In [42]:
#define target
y = df['SalePrice']

X = df.drop('SalePrice', axis=1)

In [ ]:
#ordinal encoder for ExterQual & KitchenQual
ordinal_order = ['Po' , 'Fa', 'TA', 'Gd', 'Ex']

ordinal = OrdinalEncoder(categories=[ordinal_order, ordinal_order])

#OneHot for Neighborhood
one_hot = OneHotEncoder(drop='first', sparse_output=False)

ordinal_column_transfo = ColumnTransformer(transformers=[                                           
                                            ['ordinal_preprocess', ordinal, ['KitchenQual', 'ExterQual']],
                                            ['one_hot_preprocess', one_hot, ['Neighborhood']]
                                            ],
                                            remainder='passthrough'
                                        )

In [40]:
ordinal_column_transfo.fit_transform(df)

array([[3.00000e+00, 3.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.45000e+03, 2.08500e+05],
       [2.00000e+00, 2.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        9.60000e+03, 1.81500e+05],
       [3.00000e+00, 3.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.12500e+04, 2.23500e+05],
       ...,
       [2.00000e+00, 2.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        7.91700e+03, 1.75000e+05],
       [3.00000e+00, 4.00000e+00, 0.00000e+00, ..., 2.00000e+00,
        9.04200e+03, 2.66500e+05],
       [3.00000e+00, 2.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        9.71700e+03, 1.42125e+05]], shape=(1180, 39))

In [ ]:
df_2 = df.drop(['KitchenQual', 'ExterQual'], axis=1)

df_2 =

,OverallQual,GrLivArea,TotalBsmtSF,1stFlrSF,YearBuilt,YearRemodAdd,GarageCars,GarageArea,FullBath,TotRmsAbvGrd,Fireplaces,LotArea,Neighborhood,SalePrice
0,7,1710,856,856,2003,2003,2,548,2,8,0,8450,CollgCr,208500
1,6,1262,1262,1262,1976,1976,2,460,2,6,1,9600,Veenker,181500
2,7,1786,920,920,2001,2002,2,608,2,6,1,11250,CollgCr,223500
3,8,1694,1686,1694,2004,2005,2,636,2,7,1,10084,Somerst,307000
4,7,1774,952,1022,1931,1950,2,468,2,8,2,6120,OldTown,129900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1175,5,1072,547,1072,2005,2005,2,525,1,5,0,3675,Edwards,145000
1176,7,1221,1221,1221,2004,2005,2,400,2,6,0,7500,Somerst,185000
1177,6,1647,953,953,1999,2000,2,460,2,7,1,7917,Gilbert,175000
1178,7,2340,1152,1188,1941,2006,1,252,2,9,2,9042,Crawfor,266500
1179,5,1078,1078,1078,1950,1996,1,240,1,5,0,9717,NAmes,142125

In [ ]:
df_2